### ISSUE TITLE
Diversifier les codes d'erreur login et rajouter une erreur

### ISSUE THREAD

**Issue by HelloThere-ImMat** [CharlelieB/transcendence_back#42]
Il faut différentier les codes d'erreurs pour le format d'un email et le 2fa d'activé (pour le moment, ils sont similaires.)

------

il faut egalement rajouter un nouveau code d'erreur (différent de tous les autres) pour le cas ou l'utilisateur renseigné est déjà connecté (sur une autre session ou page)

**Comment by ncharii** [comment]
code d'erreur : 
 deja connecter : 409
 non existant : 401
 2fa : 403
