### ISSUE TITLE
Créer un endpoint guest-register

### ISSUE THREAD

**Issue by HelloThere-ImMat** [CharlelieB/transcendence_back#43]
meme besoin que pour le guest-login, on souhaite permettre au utilisateur qui ne sont pas les hotes de creer un compte.

Seulement, il ne faut pas renvoyer de cookies, car ça remplacerai l'hote par l'utilisateur nouvellement créé.

Il faut juste ajouter l'utilisateur a la db, ne rien faire sur les cookies

**Comment by ncharii** [comment]
Le code a été implémenté dans la branche dev.

**Comment by ncharii** [comment]
https://localhost:8443/api/guest-register/
